source 'https://rubygems.org'

group :dependencies do
  gem 'json'
  gem 'rest-client'
end

group :test do
  gem 'rake'
  gem 'rack-test', '~> 0.6'
  gem 'rspec', '~> 3.0'
  gem 'rubocop', '~> 0.40'
end

